feat: Add coverage

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -80,6 +80,24 @@ jobs:
         with:
           token: ${{ secrets.CODECOV_TOKEN }}
 
+      - name: Test coverage check
+        env: 
+          TESTCOVERAGE_THRESHOLD: 20
+        run: |
+            echo "Checking test coverage"
+            totalCoverage=`go tool cover -func=coverage.out | grep total | grep -Eo '[0-9]+\.[0-9]+'`
+            echo "Total test coverage: $totalCoverage%"
+            echo "Desired threshold: $TESTCOVERAGE_THRESHOLD%"
+
+            if (( $(echo "$totalCoverage $TESTCOVERAGE_THRESHOLD" | awk '{print($1 > $2)}') )); then 
+              echo "OK"
+            else 
+              echo "The test coverage should be greater than $TESTCOVERAGE_THRESHOLD%"
+              echo "Failed"
+              exit 1
+            fi
+            
+
   build:
     name: Build Application
     runs-on: ubuntu-latest
